import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:society_voting_firebase/data/models/candidate_model.dart';
import 'package:society_voting_firebase/data/models/vote_model.dart';
import 'package:society_voting_firebase/data/models/voter_model.dart';
import 'package:society_voting_firebase/services/voting_service.dart';
import 'package:society_voting_firebase/services/auth_service.dart';

final votingServiceProvider = Provider((ref) => VotingService());
final currentVoterProvider = FutureProvider((ref) => ref.read(Provider((ref) => AuthService())).getCurrentVoter());

class VotingDashboardScreen extends ConsumerStatefulWidget {
  const VotingDashboardScreen({super.key});

  @override
  ConsumerState<VotingDashboardScreen> createState() => _VotingDashboardScreenState();
}

class _VotingDashboardScreenState extends ConsumerState<VotingDashboardScreen> {
  final Map<String, String> _selections = {}; // post -> candidateId
  bool _isSubmitting = false;

  void _submitBallot(VoterModel voter) async {
    if (_selections.length < 3) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a candidate for all posts.')),
      );
      return;
    }

    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Confirm Official Ballot'),
        content: const Text('Are you sure you want to submit your votes? This action cannot be undone.'),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Cancel')),
          ElevatedButton(onPressed: () => Navigator.pop(context, true), child: const Text('Confirm Submit')),
        ],
      ),
    );

    if (confirmed == true) {
      setState(() => _isSubmitting = true);
      try {
        final votes = _selections.entries.map((e) => VoteModel(
          id: '', // Generated by Firestore
          voterId: voter.uid,
          flatId: voter.flatId,
          candidateId: e.value,
          post: e.key,
          timestamp: DateTime.now(),
        )).toList();

        await ref.read(votingServiceProvider).castVotes(
          voterId: voter.uid,
          flatId: voter.flatId,
          votes: votes,
        );

        if (mounted) {
          _showSuccessOverlay();
        }
      } catch (e) {
        setState(() => _isSubmitting = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  void _showSuccessOverlay() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => WillPopScope(
        onWillPop: () async => false,
        child: Scaffold(
          backgroundColor: const Color(0xFF0B3C5D),
          body: Center(
            child: Column(
              mainAxisAlignment: Main_AxisSize.center,
              children: [
                const Icon(Icons.check_circle, size: 100, color: Colors.white),
                const SizedBox(height: 32),
                const Text(
                  'Vote Submitted Successfully',
                  style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Colors.white),
                ),
                const SizedBox(height: 16),
                const Text(
                  'Your official ballot has been recorded.',
                  style: TextStyle(fontSize: 18, color: Colors.white70),
                ),
                const SizedBox(height: 48),
                ElevatedButton(
                  onPressed: () => Navigator.pushNamedAndRemoveUntil(context, '/', (route) => false),
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.white, foregroundColor: const Color(0xFF0B3C5D)),
                  child: const Text('Exit Session'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final voterAsync = ref.watch(currentVoterProvider);

    return Scaffold(
      backgroundColor: const Color(0xFFF2F4F6),
      appBar: AppBar(
        title: const Text('Digital Ballot', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        backgroundColor: const Color(0xFF0B3C5D),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout, color: Colors.white),
            onPressed: () => ref.read(Provider((ref) => AuthService())).signOut(),
          ),
        ],
      ),
      body: voterAsync.when(
        data: (voter) {
          if (voter == null) return const Center(child: Text('Voter data not found.'));
          if (voter.hasVoted) return const Center(child: Text('You have already cast your vote.'));

          return StreamBuilder<List<CandidateModel>>(
            stream: ref.read(votingServiceProvider).getApprovedCandidates(),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
              }
              final candidates = snapshot.data ?? [];
              final posts = ['President', 'Secretary', 'Treasurer'];

              return SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Card(
                      child: ListTile(
                        leading: const Icon(Icons.person),
                        title: Text(voter.name),
                        subtitle: Text('Flat ${voter.blockNumber}-${voter.flatNumber}'),
                      ),
                    ),
                    const SizedBox(height: 24),
                    ...posts.map((post) {
                      final postCandidates = candidates.where((c) => c.post == post).toList();
                      return Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 8),
                            child: Text(
                              post,
                              style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: Color(0xFF0B3C5D)),
                            ),
                          ),
                          ...postCandidates.map((c) => Card(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                              side: BorderSide(
                                color: _selections[post] == c.id ? const Color(0xFF0B3C5D) : Colors.transparent,
                                width: 2,
                              ),
                            ),
                            child: RadioListTile<String>(
                              value: c.id,
                              groupValue: _selections[post],
                              title: Text(c.name, style: const TextStyle(fontWeight: FontWeight.bold)),
                              subtitle: Text(c.summary, maxLines: 2, overflow: TextOverflow.ellipsis),
                              secondary: CircleAvatar(backgroundImage: NetworkImage(c.photoUrl)),
                              onChanged: (val) => setState(() => _selections[post] = val!),
                            ),
                          )),
                          const Divider(height: 32),
                        ],
                      );
                    }).toList(),
                    const SizedBox(height: 32),
                    SizedBox(
                      width: double.infinity,
                      height: 60,
                      child: ElevatedButton(
                        onPressed: _isSubmitting ? null : () => _submitBallot(voter),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF0B3C5D),
                          foregroundColor: Colors.white,
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                        ),
                        child: _isSubmitting 
                          ? const CircularProgressIndicator(color: Colors.white)
                          : const Text('CAST OFFICIAL VOTE', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                      ),
                    ),
                    const SizedBox(height: 40),
                  ],
                ),
              );
            },
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => Center(child: Text('Error: $e')),
      ),
    );
  }
}
